apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wv4g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wv4g
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wv4g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wv4g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wv4g
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mymr-tenant/rhtap-demo-app/hacbs-test-project-wv4g@sha256:df2385f2f89b9eb7e648d133522210097dd1b8d9fe2e38dab824b515af936ed9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
